# 工作流名称
name: Sync-Images-to-AliYunDockerRegistry
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to AliYun Docker Registry.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to AliYun Docker Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to AliYun Docker Registry
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://hub.icert.top/opensearchproject/opensearch:2.19.1 docker://registry.cn-hangzhou.aliyuncs.com/lue/opensearch:2.19.1
        skopeo copy --all docker://infiniflow/infinity:v0.7.0-dev2 docker://registry.cn-hangzhou.aliyuncs.com/lue/infinity:v0.7.0-dev2
        skopeo copy --all docker://oceanbase/oceanbase-ce:4.4.1.0-100000032025101610 docker://registry.cn-hangzhou.aliyuncs.com/lue/oceanbase-ce:4.4.1.0-100000032025101610
        skopeo copy --all docker://oceanbase/seekdb:latest docker://registry.cn-hangzhou.aliyuncs.com/lue/seekdb:latest
        skopeo copy --all docker://mysql:8.0.39 docker://registry.cn-hangzhou.aliyuncs.com/lue/mysql:8.0.39
        skopeo copy --all docker://quay.io/minio/minio:RELEASE.2025-06-13T11-33-47Z docker://registry.cn-hangzhou.aliyuncs.com/lue/minio:RELEASE.2025-06-13T11-33-47Z
        skopeo copy --all docker://valkey/valkey:8 docker://registry.cn-hangzhou.aliyuncs.com/lue/valkey:8
        skopeo copy --all docker://elasticsearch:8.11.3 docker://registry.cn-hangzhou.aliyuncs.com/lue/elasticsearch:8.11.3
        skopeo copy --all docker://kibana:8.11.3 docker://registry.cn-hangzhou.aliyuncs.com/lue/kibana:8.11.3
        skopeo copy --all docker://infiniflow/ragflow:v0.24.0 docker://registry.cn-hangzhou.aliyuncs.com/lue/ragflow:v0.24.0
        skopeo copy --all docker://infiniflow/sandbox-executor-manager:latest docker://registry.cn-hangzhou.aliyuncs.com/lue/sandbox-executor-manager:latest
        skopeo copy --all docker://infiniflow/sandbox-base-python:latest docker://registry.cn-hangzhou.aliyuncs.com/lue/sandbox-base-python:latest
        skopeo copy --all docker://infiniflow/sandbox-base-nodejs:latest docker://registry.cn-hangzhou.aliyuncs.com/lue/sandbox-base-nodejs:latest
        skopeo copy --all docker://infiniflow/text-embeddings-inference:cpu-1.8 docker://registry.cn-hangzhou.aliyuncs.com/lue/text-embeddings-inference:cpu-1.8
        skopeo copy --all docker://infiniflow/text-embeddings-inference:1.8 docker://registry.cn-hangzhou.aliyuncs.com/lue/text-embeddings-inference:1.8
